six_data:
  outputs:
    dev:
      type: sqlserver
      host: localhost
      port: 1433
      user: sa
      password: <SECRET>
      database: WillibaldDwh
      schema: dbo
      driver: "ODBC Driver 17 for SQL Server"
      trust_cert: true
      threads: 1

  target: dev
