{{ config(alias='blue_chips_closing') }}
SELECT
    AccruedInterestFromDate
    , AllocatedNumber
    , AmountInIssue
    , AmountInIssueCHF
    , AskBookCumulatedNumOffers
    , AskBookCumulatedNumOrders
    , AskBookCumulatedVolume
    , AskBookNumOffers
    , AskBookNumOrders
    , AskBookNumQuotes
    , AskBookPrice
    , AskBookVolume
    , AskPrice
    , AskVolume
    , AssetClassCode
    , AssetClassDesc
    , BidBookCumulatedNumOffers
    , BidBookCumulatedNumOrders
    , BidBookCumulatedVolume
    , BidBookNumOffers
    , BidBookNumOrders
    , BidBookNumQuotes
    , BidBookPrice
    , BidBookVolume
    , BidPrice
    , BidVolume
    , BoardId
    , CHFEURRate
    , ClobTrades
    , ClobTurnover
    , ClobVolume
    , CloseFixingDate
    , CloseFixingPrice
    , CloseFixingTime
    , ClosingDelta
    , ClosingPerformance
    , ClosingPrice
    , ClosingPriceCHF
    , Currency
    , CurrencyRateCHF
    , CurrencyRateEUR
    , DailyHighPrice
    , DailyHighTime
    , DailyLowPrice
    , DailyLowTime
    , DeliveryTypeCode
    , DerivativeLinkTypeCode
    , DerivativeLinkTypeDesc
    , DividendEntitlementFlag
    , DividendFrequencyCode
    , DurationToWorst
    , EarliestExerciseDate
    , EarliestRedemptionDate
    , EbboTrades
    , EbboTurnover
    , EbboVolume
    , EntitlesToUnit
    , Exchange
    , ExchangeCode
    , FourdInstrumentId
    , FourdIssuerId
    , FourdSecurityId
    , GeographicalAreaCode
    , GeographicalAreaDesc
    , GuaranteeTypeCode
    , GuaranteeTypeDesc
    , HolidayCalendar
    , ICBIndustry
    , ICBIndustryDesc
    , ICBSupersector
    , ICBSupersectorDesc
    , IndustrySectorCode
    , IndustrySectorDesc
    , InstrumentTypeCode
    , InterestFrequencyCode
    , ISIN
    , IssueCurrencyCode
    , IssuerLongNameCode
    , IssuerLongNameDesc
    , IssuerNameFull
    , IssuerNameShort
    , IssueYear
    , KnockOutFlag
    , LastAskPrice
    , LastAskVolume
    , LastBidPrice
    , LastBidVolume
    , LastMidPrice
    , LastTradingDate
    , LatestExerciseDate
    , LatestTradeDate
    , LatestTradeDelta
    , LatestTradePerformance
    , LatestTradeTime
    , LatestTradeVolume
    , LegalStructureCountryCode
    , LegalStructureCountryDesc
    , ListingMemberOrgAbbrev
    , ListingSegmentCode
    , ListingSegmentDesc
    , ListingTypeCode
    , ListingTypeDesc
    , ManagementFee
    , ManagementStyleDesc
    , MarketCode
    , MarketCodeOfPublication
    , MarketDate
    , MarketMakerIds
    , MarketMakers
    , MarketPhase
    , MarketSegment
    , MarketTime
    , MaturityDate
    , MaxInterestRate
    , MidPrice
    , MidSpread
    , MinHistoryDate
    , MinInterestRate
    , MinmNeeded
    , MinOrderQty
    , MonthAgoDate
    , MonthAgoDelta
    , MonthAgoPerformance
    , MonthAgoPrice
    , NominalCurrency
    , NominalValue
    , NumberInIssue
    , NumberNeeded
    , OffBookTrades
    , OffBookTurnover
    , OffBookVolume
    , OfficialClosingPrice
    , OfficialOpeningTime
    , OnBookSource
    , OnMarketTrades
    , OnMarketTurnover
    , OnMarketVolume
    , OpeningPrice
    , OpeningTime
    , OptionTypeDesc
    , OrderbookDepth
    , PaymentDate
    , PortalSegment
    , PreviousClosingDate
    , PreviousClosingPrice
    , PreviousMarketDate
    , PreviousTradeDate
    , PreviousTradePrice
    , PrevYearlyHighPrice
    , PrevYearlyHighDate
    , PrevYearlyLowPrice
    , PrevYearlyLowDate
    , PriceStepGroupCode
    , PriceStepGroupDesc
    , ProductDescriptionShortSD
    , ProductLine
    , ProductLineDesc
    , ProductNameSD
    , ProductPriority
    , SecDescriptionFull
    , SecDescriptionFullAlt
    , SecTypeCode
    , SecTypeDesc
    , SecurityExchange
    , SecurityId
    , SettlementCycleDays
    , ShareCountType
    , ShortName
    , ShortNameAlt
    , ShortNameRDI
    , ShortName4D
    , ShortNameID
    , ShortNameSD
    , SmallestDenomination
    , SmallestTradeableUnit
    , SpecialFlag
    , SpecialFlagDesc
    , SpecialitiesDesc
    , StopTradingDuration
    , StopTradingRange
    , StopTradingRangeType
    , SubscriptionPaymentDueDate
    , SVSPSecTypeCode
    , SwissAtMidRatioOnMarket
    , SwissAtMidRatioTotal
    , SwissAtMidTrades
    , SwissAtMidTurnover
    , SwissAtMidVolume
    , TickDateTime
    , TickMillis
    , TitleSegment
    , TitleSegmentDesc
    , Tminus1Trades
    , Tminus1Turnover
    , Tminus1Volume
    , TminusNTrades
    , TminusNTurnover
    , TminusNVolume
    , TotalTrades
    , TotalTurnover
    , TotalTurnoverCHF
    , TotalVolume
    , TradingBaseCurrency
    , TradingCurrency
    , TradingSegmentId
    , TradingState
    , TurnoverGroup
    , UnitsForEntitlement
    , ValorId
    , ValorNumber
    , ValorSymbol
    , ValorSymbolAlt
    , VisibilityFlag
    , WarrantSpecialClause
    , WeekAgoDate
    , WeekAgoDelta
    , WeekAgoPerformance
    , WeekAgoPrice
    , YearAgoDate
    , YearAgoDelta
    , YearAgoPerformance
    , YearAgoPrice
    , YearEndDate
    , YearEndPrice
    , YearToDateDelta
    , YearToDatePerformance
    , YearlyHighDate
    , YearlyHighPrice
    , YearlyLowDate
    , YearlyLowPrice
    , YieldToWorst
    , LoadDate
FROM {{ source('marketdata', 'BlueChipsClosing') }}
